### ISSUE TITLE
package markups module with pyinstaller

### ISSUE THREAD

**Issue by zhangchunlu** [retext-project/pymarkups#5]
Why does my markups module run differently than the source code run when I package it with pyinstaller.
For example,
![image](https://user-images.githubusercontent.com/36025697/53538352-4a323800-3b48-11e9-9bf7-fc2ac407bd3f.png)
Use the following command to package：
pyinstaller -F markups_test.py

The results are as follows：
![image](https://user-images.githubusercontent.com/36025697/53538495-d5abc900-3b48-11e9-8559-7a1332083543.png)

**Comment by mitya57** [comment]
`markups.get_available_markups` uses the [entry points](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) mechanism to discover supported markups.

I do not use PyInstaller — maybe it needs some special configuration to handle entry points, or maybe it does not support them at all?

As a workaround, you can try using `markups.builtin_markups` instead of `markups.get_available_markups()`.

**Comment by zhangchunlu** [comment]
Thank you for your reply. May I ask which tool you use to package the source code of the retext-project? Because every time you use the retext tool, you have to install the relevant python environment, which is very troublesome

**Comment by zhangchunlu** [comment]
> `markups.get_available_markups` uses the [entry points](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) mechanism to discover supported markups.
> 
> I do not use PyInstaller — maybe it needs some special configuration to handle entry points, or maybe it does not support them at all?
> 
> As a workaround, you can try using `markups.builtin_markups` instead of `markups.get_available_markups()`.
